/*
 * Just some references to various settings
 * 
 * --Jacob Allen
 */
public enum SettingField
{
    DIAMETER, TIME_OFFSET, FACE_COLOR,
    
    HOUR_LENGTH, HOUR_WIDTH, HOUR_COLOR, HOUR_PRESENT,
    MIN_LENGTH, MIN_WIDTH, MIN_COLOR, MIN_PRESENT,
    SEC_LENGTH, SEC_WIDTH, SEC_COLOR, SEC_PRESENT,
    
    CARD_NUM_PRESENT, CARD_MARK_FONT, CARD_MARK_FONT_EMP, CARD_MARK_FONT_SIZE, CARD_MARK_ROMAN, CARD_MARK_DIST,
        CARD_MARK_COLOR, CARD_TICK_PRESENT, CARD_MARK_TICK_WIDTH, CARD_MARK_TICK_LENGTH, CARD_MARK_TICK_COLOR,
    HOUR_NUM_PRESENT, HOUR_MARK_FONT, HOUR_MARK_FONT_EMP, HOUR_MARK_FONT_SIZE, HOUR_MARK_ROMAN, HOUR_MARK_DIST,
        HOUR_MARK_COLOR, HOUR_TICK_PRESENT, HOUR_MARK_TICK_WIDTH, HOUR_MARK_TICK_LENGTH, HOUR_MARK_TICK_COLOR,
    MIN_NUM_PRESENT, MIN_MARK_FONT, MIN_MARK_FONT_EMP, MIN_MARK_FONT_SIZE, MIN_MARK_ROMAN, MIN_MARK_DIST,
        MIN_MARK_COLOR, MIN_TICK_PRESENT, MIN_MARK_TICK_WIDTH, MIN_MARK_TICK_LENGTH, MIN_MARK_TICK_COLOR
}
